"""create initial tables

Revision ID: e0d75b15bec7
Revises:
Create Date: 2026-05-06 11:19:05.646046+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e0d75b15bec7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_users_phone"), "admin_users", ["phone"], unique=True)
    op.create_index(op.f("ix_admin_users_status"), "admin_users", ["status"], unique=False)
    op.create_index(op.f("ix_admin_users_username"), "admin_users", ["username"], unique=True)
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("udid", sa.String(length=128), nullable=False),
        sa.Column("system_port", sa.Integer(), nullable=False),
        sa.Column("enabled_status", sa.String(length=20), nullable=False),
        sa.Column("runtime_status", sa.String(length=20), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remark", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("system_port"),
    )
    op.create_index(op.f("ix_devices_enabled_status"), "devices", ["enabled_status"], unique=False)
    op.create_index(op.f("ix_devices_name"), "devices", ["name"], unique=True)
    op.create_index(op.f("ix_devices_runtime_status"), "devices", ["runtime_status"], unique=False)
    op.create_index(op.f("ix_devices_udid"), "devices", ["udid"], unique=True)
    op.create_table(
        "doctors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("remark", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_doctors_name"), "doctors", ["name"], unique=False)
    op.create_index(op.f("ix_doctors_status"), "doctors", ["status"], unique=False)
    op.create_table(
        "daily_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("stopped_count", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["admin_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_daily_tasks_status"), "daily_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_daily_tasks_task_date"), "daily_tasks", ["task_date"], unique=False)
    op.create_index(
        "ix_daily_tasks_task_date_status", "daily_tasks", ["task_date", "status"], unique=False
    )
    op.create_table(
        "doctor_keywords",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("keyword", sa.String(length=100), nullable=False),
        sa.Column("remark", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doctor_id", "keyword", name="uq_doctor_keyword"),
    )
    op.create_index(
        op.f("ix_doctor_keywords_doctor_id"), "doctor_keywords", ["doctor_id"], unique=False
    )
    op.create_index(
        op.f("ix_doctor_keywords_keyword"), "doctor_keywords", ["keyword"], unique=False
    )
    op.create_index(op.f("ix_doctor_keywords_status"), "doctor_keywords", ["status"], unique=False)
    op.create_table(
        "comment_bank_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.Column("search_word", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("used_device_id", sa.Integer(), nullable=True),
        sa.Column("used_account", sa.String(length=100), nullable=True),
        sa.Column("used_task_id", sa.Integer(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["doctor_keywords.id"],
        ),
        sa.ForeignKeyConstraint(
            ["used_device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["used_task_id"],
            ["daily_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_comment_bank_doctor_keyword_status",
        "comment_bank_items",
        ["doctor_id", "keyword_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_comment_bank_items_doctor_id"), "comment_bank_items", ["doctor_id"], unique=False
    )
    op.create_index(
        op.f("ix_comment_bank_items_keyword_id"), "comment_bank_items", ["keyword_id"], unique=False
    )
    op.create_index(
        op.f("ix_comment_bank_items_search_word"),
        "comment_bank_items",
        ["search_word"],
        unique=False,
    )
    op.create_index(
        op.f("ix_comment_bank_items_status"), "comment_bank_items", ["status"], unique=False
    )
    op.create_table(
        "daily_task_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("claimed_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["doctor_keywords.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["daily_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_task_items_doctor_id"), "daily_task_items", ["doctor_id"], unique=False
    )
    op.create_index(
        "ix_daily_task_items_doctor_keyword",
        "daily_task_items",
        ["doctor_id", "keyword_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_task_items_keyword_id"), "daily_task_items", ["keyword_id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_task_items_status"), "daily_task_items", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_daily_task_items_task_id"), "daily_task_items", ["task_id"], unique=False
    )
    op.create_index(
        "ix_daily_task_items_task_status", "daily_task_items", ["task_id", "status"], unique=False
    )
    op.create_table(
        "automation_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("task_item_id", sa.Integer(), nullable=True),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("comment_bank_item_id", sa.Integer(), nullable=True),
        sa.Column("publish_account", sa.String(length=100), nullable=False),
        sa.Column("comment_content", sa.Text(), nullable=False),
        sa.Column("video_link", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("fail_reason", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("screenshot_url", sa.String(length=512), nullable=True),
        sa.Column("log_url", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(
            ["comment_bank_item_id"],
            ["comment_bank_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["doctor_keywords.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["daily_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_item_id"],
            ["daily_task_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_automation_results_device_id"), "automation_results", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_automation_results_doctor_id"), "automation_results", ["doctor_id"], unique=False
    )
    op.create_index(
        "ix_automation_results_doctor_keyword",
        "automation_results",
        ["doctor_id", "keyword_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_results_keyword_id"), "automation_results", ["keyword_id"], unique=False
    )
    op.create_index(
        op.f("ix_automation_results_status"), "automation_results", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_automation_results_task_id"), "automation_results", ["task_id"], unique=False
    )
    op.create_index(
        "ix_automation_results_task_status",
        "automation_results",
        ["task_id", "status"],
        unique=False,
    )
    op.create_table(
        "comment_recheck_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("automation_result_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fail_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(
            ["automation_result_id"],
            ["automation_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comment_recheck_records_automation_result_id"),
        "comment_recheck_records",
        ["automation_result_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_comment_recheck_records_status"),
        "comment_recheck_records",
        ["status"],
        unique=False,
    )
    op.create_table(
        "device_doctor_action_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("result_id", sa.Integer(), nullable=True),
        sa.Column("action_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("acted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["doctor_keywords.id"],
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["automation_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["daily_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "device_id",
            "doctor_id",
            "keyword_id",
            "action_type",
            name="uq_device_doctor_keyword_action",
        ),
    )
    op.create_index(
        "ix_device_action_doctor_keyword",
        "device_doctor_action_records",
        ["doctor_id", "keyword_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_doctor_action_records_device_id"),
        "device_doctor_action_records",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_doctor_action_records_doctor_id"),
        "device_doctor_action_records",
        ["doctor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_doctor_action_records_keyword_id"),
        "device_doctor_action_records",
        ["keyword_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_doctor_action_records_status"),
        "device_doctor_action_records",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_device_doctor_action_records_status"), table_name="device_doctor_action_records"
    )
    op.drop_index(
        op.f("ix_device_doctor_action_records_keyword_id"),
        table_name="device_doctor_action_records",
    )
    op.drop_index(
        op.f("ix_device_doctor_action_records_doctor_id"), table_name="device_doctor_action_records"
    )
    op.drop_index(
        op.f("ix_device_doctor_action_records_device_id"), table_name="device_doctor_action_records"
    )
    op.drop_index("ix_device_action_doctor_keyword", table_name="device_doctor_action_records")
    op.drop_table("device_doctor_action_records")
    op.drop_index(op.f("ix_comment_recheck_records_status"), table_name="comment_recheck_records")
    op.drop_index(
        op.f("ix_comment_recheck_records_automation_result_id"),
        table_name="comment_recheck_records",
    )
    op.drop_table("comment_recheck_records")
    op.drop_index("ix_automation_results_task_status", table_name="automation_results")
    op.drop_index(op.f("ix_automation_results_task_id"), table_name="automation_results")
    op.drop_index(op.f("ix_automation_results_status"), table_name="automation_results")
    op.drop_index(op.f("ix_automation_results_keyword_id"), table_name="automation_results")
    op.drop_index("ix_automation_results_doctor_keyword", table_name="automation_results")
    op.drop_index(op.f("ix_automation_results_doctor_id"), table_name="automation_results")
    op.drop_index(op.f("ix_automation_results_device_id"), table_name="automation_results")
    op.drop_table("automation_results")
    op.drop_index("ix_daily_task_items_task_status", table_name="daily_task_items")
    op.drop_index(op.f("ix_daily_task_items_task_id"), table_name="daily_task_items")
    op.drop_index(op.f("ix_daily_task_items_status"), table_name="daily_task_items")
    op.drop_index(op.f("ix_daily_task_items_keyword_id"), table_name="daily_task_items")
    op.drop_index("ix_daily_task_items_doctor_keyword", table_name="daily_task_items")
    op.drop_index(op.f("ix_daily_task_items_doctor_id"), table_name="daily_task_items")
    op.drop_table("daily_task_items")
    op.drop_index(op.f("ix_comment_bank_items_status"), table_name="comment_bank_items")
    op.drop_index(op.f("ix_comment_bank_items_search_word"), table_name="comment_bank_items")
    op.drop_index(op.f("ix_comment_bank_items_keyword_id"), table_name="comment_bank_items")
    op.drop_index(op.f("ix_comment_bank_items_doctor_id"), table_name="comment_bank_items")
    op.drop_index("ix_comment_bank_doctor_keyword_status", table_name="comment_bank_items")
    op.drop_table("comment_bank_items")
    op.drop_index(op.f("ix_doctor_keywords_status"), table_name="doctor_keywords")
    op.drop_index(op.f("ix_doctor_keywords_keyword"), table_name="doctor_keywords")
    op.drop_index(op.f("ix_doctor_keywords_doctor_id"), table_name="doctor_keywords")
    op.drop_table("doctor_keywords")
    op.drop_index("ix_daily_tasks_task_date_status", table_name="daily_tasks")
    op.drop_index(op.f("ix_daily_tasks_task_date"), table_name="daily_tasks")
    op.drop_index(op.f("ix_daily_tasks_status"), table_name="daily_tasks")
    op.drop_table("daily_tasks")
    op.drop_index(op.f("ix_doctors_status"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_name"), table_name="doctors")
    op.drop_table("doctors")
    op.drop_index(op.f("ix_devices_udid"), table_name="devices")
    op.drop_index(op.f("ix_devices_runtime_status"), table_name="devices")
    op.drop_index(op.f("ix_devices_name"), table_name="devices")
    op.drop_index(op.f("ix_devices_enabled_status"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_admin_users_username"), table_name="admin_users")
    op.drop_index(op.f("ix_admin_users_status"), table_name="admin_users")
    op.drop_index(op.f("ix_admin_users_phone"), table_name="admin_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
