export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    me: '/auth/me',
    logout: '/auth/logout',
  },
  adminUsers: {
    list: '/admin-users',
    create: '/admin-users',
    update: (id: number) => `/admin-users/${id}`,
    enable: (id: number) => `/admin-users/${id}/enable`,
    disable: (id: number) => `/admin-users/${id}/disable`,
    resetPassword: (id: number) => `/admin-users/${id}/reset-password`,
  },
  doctors: {
    list: '/doctors',
    options: '/doctors/options',
    create: '/doctors',
    sortOrder: '/doctors/sort-order',
    update: (id: number) => `/doctors/${id}`,
    enable: (id: number) => `/doctors/${id}/enable`,
    disable: (id: number) => `/doctors/${id}/disable`,
    delete: (id: number) => `/doctors/${id}`,
    keywords: (doctorId: number) => `/doctors/${doctorId}/keywords`,
  },
  doctorKeywords: {
    options: '/doctor-keywords/options',
    update: (id: number) => `/doctor-keywords/${id}`,
    enable: (id: number) => `/doctor-keywords/${id}/enable`,
    disable: (id: number) => `/doctor-keywords/${id}/disable`,
    delete: (id: number) => `/doctor-keywords/${id}`,
  },
  doctorProvinces: {
    list: '/doctor-provinces',
    options: '/doctor-provinces/options',
    update: (doctorId: number) => `/doctor-provinces/${doctorId}`,
  },
  regionRelations: {
    list: '/region-relations',
    options: '/region-relations/options',
    update: (id: number) => `/region-relations/${id}`,
    resetDefaults: '/region-relations/reset-defaults',
  },
  commentBank: {
    list: '/comment-bank',
    delete: (id: number) => `/comment-bank/${id}`,
    batchDelete: '/comment-bank/batch-delete',
    importExcel: '/comment-bank/import-excel',
  },
  dailyTasks: {
    list: '/daily-tasks',
    options: '/daily-tasks/options',
    create: '/daily-tasks',
    sortItems: (id: number) => `/daily-tasks/${id}/items/sort-order`,
    dispatch: (id: number) => `/daily-tasks/${id}/dispatch`,
    deviceDetails: (id: number) => `/daily-tasks/${id}/device-details`,
    stop: (id: number) => `/daily-tasks/${id}/stop`,
  },
  devices: {
    list: '/devices',
    options: '/devices/options',
    create: '/devices',
    update: (id: number) => `/devices/${id}`,
    enable: (id: number) => `/devices/${id}/enable`,
    disable: (id: number) => `/devices/${id}/disable`,
  },
  automationResults: {
    list: '/automation-results',
    export: '/automation-results/export',
    exportToDesktop: '/automation-results/export-to-desktop',
  },
  automationRuntime: {
    state: '/automation/runtime',
    services: '/automation/runtime/services',
    start: '/automation/runtime/start',
    stop: '/automation/runtime/stop',
  },
  automationTiming: {
    list: '/automation/timing-settings',
    update: '/automation/timing-settings',
    resetDefaults: '/automation/timing-settings/reset-defaults',
  },
  commentRecheck: {
    list: '/comment-results/recheck',
    start: '/comment-results/recheck',
    startToday: '/comment-results/recheck/today',
    startByDate: '/comment-results/recheck/by-date',
    startByDateRange: '/comment-results/recheck/by-date-range',
    loginStatus: '/comment-results/recheck/login-status',
    loginSession: '/comment-results/recheck/login-session',
    loginQr: '/comment-results/recheck/login-qr',
    confirmLogin: '/comment-results/recheck/confirm-login',
  },
} as const
